name: Node CI

on:
    push:
        branches: myimage
    pull_request:
        branches:
            - myimage

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - uses: actions/checkout@v1
              with:
                  ref: myimage
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: npm install, build, and test
              run: |
                  npm i -g npm
                  npm cache clean --force
                  npm ci
                  npm run build
                  npm run lint
                  npm test -- --forceExit #https://github.com/facebook/jest/issues/9982#issuecomment-758110298
              env:
                  CI: true
            - name: Check spelling
              uses: crate-ci/typos@master
